In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('../Data.csv')

In [3]:
dft = pd.read_csv('testing6.csv')

In [4]:
df.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0        71        71        64        98       150        86        68   
1        72        72        63        98       149        84        69   
2        72        75        66        98       152        82        73   
3        75        72        66        98       154        84        75   
4        74        75        65        98       159        85        79   

   channel8 label  
0       209  left  
1       205  left  
2       202  left  
3       199  left  
4       195  left

In [5]:
dft.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0       119       104       153       171        86       179       143   
1       119       104       156       167        85       178       140   
2       122       105       156       171        86       175       146   
3       121       106       156       172        84       175       140   
4       124       101       156       175        85       171       148   

   channel8 label  
0       194  left  
1       201  left  
2       194  left  
3       203  left  
4       195  left

In [6]:
from sklearn.svm import SVC

In [7]:
model = SVC()

In [8]:
model.fit(df.drop('label',axis=1),df['label'])

SVC()

In [9]:
predictions = model.predict(dft.drop('label',axis=1))

In [10]:
from sklearn.metrics import classification_report,confusion_matrix

In [11]:
print(confusion_matrix(dft['label'],predictions))

[[  0  10  32 136  56  16]
 [  0   3 148  84  15   0]
 [  0   2  85 147  16   0]
 [  0  18   6 224   0   2]
 [  0   0   0 250   0   0]
 [  0   0  31 202  17   0]]


In [12]:
print(classification_report(dft['label'],predictions))

              precision    recall  f1-score   support

        back       0.00      0.00      0.00       250
       front       0.09      0.01      0.02       250
        left       0.28      0.34      0.31       250
       right       0.21      0.90      0.35       250
       start       0.00      0.00      0.00       250
        stop       0.00      0.00      0.00       250

    accuracy                           0.21      1500
   macro avg       0.10      0.21      0.11      1500
weighted avg       0.10      0.21      0.11      1500



C:\Users\MDTus\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\MDTus\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\MDTus\anaconda3\envs\tf\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
