In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('../Data.csv')

In [4]:
dft = pd.read_csv('testing7.csv')

In [5]:
df.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0        71        71        64        98       150        86        68   
1        72        72        63        98       149        84        69   
2        72        75        66        98       152        82        73   
3        75        72        66        98       154        84        75   
4        74        75        65        98       159        85        79   

   channel8 label  
0       209  left  
1       205  left  
2       202  left  
3       199  left  
4       195  left

In [6]:
dft.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0        73        80        78        82        95       111       120   
1        73        79        78        82        98       109       116   
2        73        80        77        84        98       110       122   
3        74        79        78        82        99       110       118   
4        75        80        78        83       100       110       123   

   channel8 label  
0       193  left  
1       195  left  
2       194  left  
3       197  left  
4       195  left

In [7]:
from sklearn.svm import SVC

In [8]:
model = SVC()

In [9]:
model.fit(df.drop('label',axis=1),df['label'])

SVC()

In [10]:
predictions = model.predict(dft.drop('label',axis=1))

In [11]:
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
print(confusion_matrix(dft['label'],predictions))

[[  0 109  98  41   2   0]
 [  0   0  33 216   0   1]
 [  0   1 128  83  38   0]
 [ 14  59   0 133  14  30]
 [  0   0   0 250   0   0]
 [  0   0   0 250   0   0]]


In [13]:
print(classification_report(dft['label'],predictions))

              precision    recall  f1-score   support

        back       0.00      0.00      0.00       250
       front       0.00      0.00      0.00       250
        left       0.49      0.51      0.50       250
       right       0.14      0.53      0.22       250
       start       0.00      0.00      0.00       250
        stop       0.00      0.00      0.00       250

    accuracy                           0.17      1500
   macro avg       0.11      0.17      0.12      1500
weighted avg       0.11      0.17      0.12      1500

