In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('Data.csv')

In [3]:
df.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0        71        71        64        98       150        86        68   
1        72        72        63        98       149        84        69   
2        72        75        66        98       152        82        73   
3        75        72        66        98       154        84        75   
4        74        75        65        98       159        85        79   

   channel8 label  
0       209  left  
1       205  left  
2       202  left  
3       199  left  
4       195  left

In [4]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('label',axis=1) , df['label'], test_size=0.25)
print('Splitted Successfully')

Splitted Successfully


In [14]:
from sklearn.svm import SVC

In [15]:
model = SVC()

In [16]:
model.fit(X_train,y_train)

SVC()

In [17]:
predictions = model.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
print(confusion_matrix(y_test,predictions))

[[663  13   2   9   4  56]
 [ 46 629  11   8   8  19]
 [ 41  36 556  39  22  52]
 [ 27  88  10 576  14  46]
 [ 33  40  14  16 618  40]
 [125  63  12  18  25 521]]


In [20]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

        back       0.71      0.89      0.79       747
       front       0.72      0.87      0.79       721
        left       0.92      0.75      0.82       746
       right       0.86      0.76      0.81       761
       start       0.89      0.81      0.85       761
        stop       0.71      0.68      0.70       764

    accuracy                           0.79      4500
   macro avg       0.80      0.79      0.79      4500
weighted avg       0.80      0.79      0.79      4500



In [13]:
# a = np.arange(0.01, 1, 0.01)
# b = np.arange(0.01, 1, 0.01)

In [14]:
# a = a[::-1]

In [21]:
# param_grid = {'C': a, 'gamma': b, 'kernel': ['rbf']} 
param_grid = {'C': [0.1,1,2, 10, 100, 1000, 1050, 2000, 2500], 'gamma': [1,0.1,0.01,0.00101, 0.001,0.005,0.0001], 'kernel': ['rbf']} 

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [24]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 63 candidates, totalling 315 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.169 total time=  23.2s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.169 total time=  23.3s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.169 total time=  23.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.169 total time=  24.1s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.169 total time=  34.2s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.169 total time=  29.7s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.169 total time=  30.8s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.169 total time=  25.4s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.169 total time=  29.8s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.169 total time=  28.6s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.174 total time=  23.8s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 2/5] END .....C=2, gamma=0.0001, kernel=rbf;, score=0.913 total time=   3.9s
[CV 3/5] END .....C=2, gamma=0.0001, kernel=rbf;, score=0.911 total time=   3.9s
[CV 4/5] END .....C=2, gamma=0.0001, kernel=rbf;, score=0.906 total time=   3.8s
[CV 5/5] END .....C=2, gamma=0.0001, kernel=rbf;, score=0.917 total time=   4.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.171 total time=  20.8s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.172 total time=  20.8s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.171 total time=  21.2s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.172 total time=  20.8s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.171 total time=  20.7s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.521 total time=  20.7s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.524 total time=  20.2s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.532 total time=  20.9s
[CV 4/5] END .......C=10, ga

[CV 4/5] END ...C=1000, gamma=0.005, kernel=rbf;, score=0.991 total time=  16.3s
[CV 5/5] END ...C=1000, gamma=0.005, kernel=rbf;, score=0.987 total time=  15.5s
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.994 total time=   2.9s
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.996 total time=   3.0s
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.997 total time=   3.0s
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.996 total time=   3.0s
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.997 total time=   3.0s
[CV 1/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.171 total time=  21.2s
[CV 2/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.172 total time=  21.0s
[CV 3/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.171 total time=  20.8s
[CV 4/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.172 total time=  20.8s
[CV 5/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.171 total time=  21.0s
[CV 1/5] END .....C=1050, ga

[CV 1/5] END ...C=2500, gamma=0.005, kernel=rbf;, score=0.991 total time=  16.0s
[CV 2/5] END ...C=2500, gamma=0.005, kernel=rbf;, score=0.991 total time=  16.3s
[CV 3/5] END ...C=2500, gamma=0.005, kernel=rbf;, score=0.987 total time=  15.3s
[CV 4/5] END ...C=2500, gamma=0.005, kernel=rbf;, score=0.991 total time=  17.1s
[CV 5/5] END ...C=2500, gamma=0.005, kernel=rbf;, score=0.987 total time=  16.1s
[CV 1/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.994 total time=   2.9s
[CV 2/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.996 total time=   2.9s
[CV 3/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.997 total time=   2.9s
[CV 4/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.996 total time=   2.9s
[CV 5/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.995 total time=   2.9s


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 2, 10, 100, 1000, 1050, 2000, 2500],
                         'gamma': [1, 0.1, 0.01, 0.00101, 0.001, 0.005, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [25]:
grid.best_params_

{'C': 10, 'gamma': 0.00101, 'kernel': 'rbf'}

In [26]:
grid.best_estimator_

SVC(C=10, gamma=0.00101)

In [27]:
grid_predictions = grid.predict(X_test)

In [28]:
print(confusion_matrix(y_test,predictions))

[[663  13   2   9   4  56]
 [ 46 629  11   8   8  19]
 [ 41  36 556  39  22  52]
 [ 27  88  10 576  14  46]
 [ 33  40  14  16 618  40]
 [125  63  12  18  25 521]]


In [29]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

        back       0.71      0.89      0.79       747
       front       0.72      0.87      0.79       721
        left       0.92      0.75      0.82       746
       right       0.86      0.76      0.81       761
       start       0.89      0.81      0.85       761
        stop       0.71      0.68      0.70       764

    accuracy                           0.79      4500
   macro avg       0.80      0.79      0.79      4500
weighted avg       0.80      0.79      0.79      4500

