In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('normal person training dataset.csv')

In [3]:
dft = pd.read_csv('patients testing dataset.csv')

In [4]:
df.head()

Channel1  channel2  channel3  channel4  channel5  channel6 Label
0        86        93        71        71        76        57  left
1        84        92        72        72        73        54  left
2        82        91        71        73        69        53  left
3        81        90        70        73        66        54  left
4        79        87        69        73        65        55  left

In [5]:
dft.head()

channel1  channel2  channel3  channel4  channel5  channel6 label
0        57        58        64        57        62       120  left
1        58        60        67        58        62       118  left
2        58        59        69        59        61       115  left
3        59        58        73        62        60       115  left
4        59        58        70        59        62       113  left

In [6]:
from sklearn.svm import SVC

In [7]:
model = SVC()

In [8]:
model.fit(df.drop('Label',axis=1),df['Label'])

SVC()

In [9]:
predictions = model.predict(dft.drop('label',axis=1))

In [10]:
from sklearn.metrics import classification_report,confusion_matrix

In [11]:
print(confusion_matrix(dft['label'],predictions))

[[ 93   0   0   0   0   9]
 [  0  82   0   0  19   0]
 [ 22   0  15  63   0   0]
 [  3   3   0  95   0   0]
 [  0   6   0  51  44   0]
 [  0   1   0   0   0 100]]


In [12]:
print(classification_report(dft['label'],predictions))

              precision    recall  f1-score   support

        back       0.79      0.91      0.85       102
       front       0.89      0.81      0.85       101
        left       1.00      0.15      0.26       100
       right       0.45      0.94      0.61       101
       start       0.70      0.44      0.54       101
        stop       0.92      0.99      0.95       101

    accuracy                           0.71       606
   macro avg       0.79      0.71      0.68       606
weighted avg       0.79      0.71      0.68       606



In [13]:
# a = np.arange(0.01, 1, 0.01)
# b = np.arange(0.01, 1, 0.01)

In [14]:
# a = a[::-1]

In [15]:
# param_grid = {'C': a, 'gamma': b, 'kernel': ['rbf']} 
param_grid = {'C': [0.1,1,2, 10, 100, 1000, 1050, 2000, 2500], 'gamma': [1,0.1,0.01,0.00101, 0.001,0.005,0.0001], 'kernel': ['rbf']} 

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [18]:
grid.fit(df.drop('Label',axis=1),df['Label'])

Fitting 5 folds for each of 63 candidates, totalling 315 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.531 total time=   1.1s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.579 total time=   0.9s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.667 total time=   0.9s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.612 total time=   0.9s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.676 total time=   0.9s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.512 total time=   0.7s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.668 total time=   0.7s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.647 total time=   0.7s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.650 total time=   0.7s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.570 total time=   0.7s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.622 total time=   0.3s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

[CV 2/5] END .....C=2, gamma=0.0001, kernel=rbf;, score=0.858 total time=   0.1s
[CV 3/5] END .....C=2, gamma=0.0001, kernel=rbf;, score=0.871 total time=   0.0s
[CV 4/5] END .....C=2, gamma=0.0001, kernel=rbf;, score=0.952 total time=   0.1s
[CV 5/5] END .....C=2, gamma=0.0001, kernel=rbf;, score=0.798 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.759 total time=   0.6s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.883 total time=   0.6s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.883 total time=   0.6s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.815 total time=   0.6s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.855 total time=   0.6s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.777 total time=   0.4s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.893 total time=   0.4s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.909 total time=   0.4s
[CV 4/5] END .......C=10, ga

[CV 5/5] END ...C=1000, gamma=0.005, kernel=rbf;, score=0.817 total time=   0.1s
[CV 1/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.637 total time=   0.0s
[CV 2/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.909 total time=   0.0s
[CV 3/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.917 total time=   0.1s
[CV 4/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.936 total time=   0.0s
[CV 5/5] END ..C=1000, gamma=0.0001, kernel=rbf;, score=0.833 total time=   0.0s
[CV 1/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.759 total time=   0.6s
[CV 2/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.883 total time=   0.6s
[CV 3/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.883 total time=   0.7s
[CV 4/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.815 total time=   0.6s
[CV 5/5] END .......C=1050, gamma=1, kernel=rbf;, score=0.855 total time=   0.7s
[CV 1/5] END .....C=1050, gamma=0.1, kernel=rbf;, score=0.777 total time=   0.5s
[CV 2/5] END .....C=1050, ga

[CV 3/5] END ...C=2500, gamma=0.005, kernel=rbf;, score=0.868 total time=   0.1s
[CV 4/5] END ...C=2500, gamma=0.005, kernel=rbf;, score=0.970 total time=   0.1s
[CV 5/5] END ...C=2500, gamma=0.005, kernel=rbf;, score=0.817 total time=   0.1s
[CV 1/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.639 total time=   0.0s
[CV 2/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.917 total time=   0.0s
[CV 3/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.931 total time=   0.0s
[CV 4/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.934 total time=   0.0s
[CV 5/5] END ..C=2500, gamma=0.0001, kernel=rbf;, score=0.835 total time=   0.1s


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 2, 10, 100, 1000, 1050, 2000, 2500],
                         'gamma': [1, 0.1, 0.01, 0.00101, 0.001, 0.005, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [19]:
grid.best_params_

{'C': 1000, 'gamma': 0.00101, 'kernel': 'rbf'}

In [20]:
grid.best_estimator_

SVC(C=1000, gamma=0.00101)

In [21]:
grid_predictions = grid.predict(dft.drop('label',axis=1))

In [22]:
print(confusion_matrix(dft['label'],predictions))

[[ 93   0   0   0   0   9]
 [  0  82   0   0  19   0]
 [ 22   0  15  63   0   0]
 [  3   3   0  95   0   0]
 [  0   6   0  51  44   0]
 [  0   1   0   0   0 100]]


In [23]:
print(classification_report(dft['label'],predictions))

              precision    recall  f1-score   support

        back       0.79      0.91      0.85       102
       front       0.89      0.81      0.85       101
        left       1.00      0.15      0.26       100
       right       0.45      0.94      0.61       101
       start       0.70      0.44      0.54       101
        stop       0.92      0.99      0.95       101

    accuracy                           0.71       606
   macro avg       0.79      0.71      0.68       606
weighted avg       0.79      0.71      0.68       606

