In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('../Data.csv')

In [3]:
dft = pd.read_csv('testing3.csv')

In [4]:
df.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0        71        71        64        98       150        86        68   
1        72        72        63        98       149        84        69   
2        72        75        66        98       152        82        73   
3        75        72        66        98       154        84        75   
4        74        75        65        98       159        85        79   

   channel8 label  
0       209  left  
1       205  left  
2       202  left  
3       199  left  
4       195  left

In [5]:
dft.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0       139        88       166       169        86       157       168   
1       139        91       168       168        85       156       164   
2       136        91       164       173        85       147       172   
3       137        91       165       170        85       149       170   
4       137        89       166       173        84       141       173   

   channel8 label  
0       206  left  
1       201  left  
2       200  left  
3       193  left  
4       198  left

In [6]:
from sklearn.svm import SVC

In [7]:
model = SVC()

In [8]:
model.fit(df.drop('label',axis=1),df['label'])

SVC()

In [9]:
predictions = model.predict(dft.drop('label',axis=1))

In [10]:
from sklearn.metrics import classification_report,confusion_matrix

In [11]:
print(confusion_matrix(dft['label'],predictions))

[[ 21  11  28 146  28  16]
 [  0   0  33 216   0   1]
 [  0   1  34 161  54   0]
 [  3   0  22 169   8  48]
 [  0   0   0 250   0   0]
 [  0   0   0 235  15   0]]


In [12]:
print(classification_report(dft['label'],predictions))

              precision    recall  f1-score   support

        back       0.88      0.08      0.15       250
       front       0.00      0.00      0.00       250
        left       0.29      0.14      0.19       250
       right       0.14      0.68      0.24       250
       start       0.00      0.00      0.00       250
        stop       0.00      0.00      0.00       250

    accuracy                           0.15      1500
   macro avg       0.22      0.15      0.10      1500
weighted avg       0.22      0.15      0.10      1500

