In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('Data.csv')

In [3]:
dft = pd.read_csv('testing3.csv')

In [4]:
df.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0        71        71        64        98       150        86        68   
1        72        72        63        98       149        84        69   
2        72        75        66        98       152        82        73   
3        75        72        66        98       154        84        75   
4        74        75        65        98       159        85        79   

   channel8 label  
0       209  left  
1       205  left  
2       202  left  
3       199  left  
4       195  left

In [5]:
dft.head()

channel1  channel2  channel3  channel4  channel5  channel6  channel7  \
0       126       161        86        71        89       107        64   
1       124       158        86        70        91       103        61   
2       122       160        86        71        94       109        59   
3       121       164        86        70        98       112        57   
4       119       159        86        72       100       110        56   

   channel8 label  
0        56  left  
1        54  left  
2        54  left  
3        53  left  
4        52  left

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
model = RandomForestClassifier()

In [8]:
model.fit(df.drop('label',axis=1),df['label'])

RandomForestClassifier()

In [9]:
predictions = model.predict(dft.drop('label',axis=1))

In [10]:
from sklearn.metrics import classification_report,confusion_matrix

In [11]:
print(confusion_matrix(dft['label'],predictions))

[[250   0   0   0   0   0]
 [  0 250   0   0   0   0]
 [  0   0 250   0   0   0]
 [  0   0   0 250   0   0]
 [  0   0   0   0 250   0]
 [  0   0   0   0   0 250]]


In [12]:
print(classification_report(dft['label'],predictions))

              precision    recall  f1-score   support

        back       1.00      1.00      1.00       250
       front       1.00      1.00      1.00       250
        left       1.00      1.00      1.00       250
       right       1.00      1.00      1.00       250
       start       1.00      1.00      1.00       250
        stop       1.00      1.00      1.00       250

    accuracy                           1.00      1500
   macro avg       1.00      1.00      1.00      1500
weighted avg       1.00      1.00      1.00      1500

